import Frigo from '../assets/frigo.webp'

export const navigation = [
  {
    id: '0',
    title: 'Home',
    url: '/',
  },
  {
    id: '1',
    title: 'About',
    url: '/about',
  },
  {
    id: '2',
    title: 'Product',
    url: '/product',
  },
]

export const products = [
  {
    id: 1,
    name: 'product_refrigeratorLG',
    href: '/singleproduct',
    category: 'category_refrigerators',
    imageSrc: Frigo, // Ensure Frigo is correctly imported
    imageAlt: 'alt_refrigeratorLG',
    price: '120000',
    color: 'Silver',
  },
  {
    id: 2,
    name: 'product_washerSamsung',
    href: '/singleproduct',
    category: 'category_washers',
    imageSrc: Frigo,
    imageAlt: 'alt_washerSamsung',
    price: '80000',
    color: 'White',
  },
  {
    id: 3,
    name: 'product_ovenBosch',
    href: '/singleproduct',
    category: 'category_ovens',
    imageSrc: Frigo,
    imageAlt: 'alt_ovenBosch',
    price: '60000',
    color: 'Black',
  },
  {
    id: 4,
    name: 'product_microwavePanasonic',
    href: '/singleproduct',
    category: 'category_microwaves',
    imageSrc: Frigo,
    imageAlt: 'alt_microwavePanasonic',
    price: '15000',
    color: 'Black',
  },
  {
    id: 5,
    name: 'product_airConditionerDaikin',
    href: '/singleproduct',
    category: 'category_airConditioners',
    imageSrc: Frigo,
    imageAlt: 'alt_airConditionerDaikin',
    price: '100000',
    color: 'White',
  },
  {
    id: 6,
    name: 'product_refrigeratorSamsung',
    href: '/singleproduct',
    category: 'category_refrigerators',
    imageSrc: Frigo,
    imageAlt: 'alt_refrigeratorSamsung',
    price: '110000',
    color: 'Silver',
  },
  {
    id: 7,
    name: 'product_washerLG',
    href: '/singleproduct',
    category: 'category_washers',
    imageSrc: Frigo,
    imageAlt: 'alt_washerLG',
    price: '85000',
    color: 'White',
  },
  {
    id: 8,
    name: 'product_ovenElectrolux',
    href: '/singleproduct',
    category: 'category_ovens',
    imageSrc: Frigo,
    imageAlt: 'alt_ovenElectrolux',
    price: '62000',
    color: 'Black',
  },
  {
    id: 9,
    name: 'product_microwaveLG',
    href: '/singleproduct',
    category: 'category_microwaves',
    imageSrc: Frigo,
    imageAlt: 'alt_microwaveLG',
    price: '16000',
    color: 'Black',
  },
  {
    id: 10,
    name: 'product_airConditionerLG',
    href: '/singleproduct',
    category: 'category_airConditioners',
    imageSrc: Frigo,
    imageAlt: 'alt_airConditionerLG',
    price: '102000',
    color: 'White',
  },
  {
    id: 11,
    name: 'product_refrigeratorBosch',
    href: '/singleproduct',
    category: 'category_refrigerators',
    imageSrc: Frigo,
    imageAlt: 'alt_refrigeratorBosch',
    price: '115000',
    color: 'Silver',
  },
]
